services:
  # OpenVSCode — CPU profile AMD
  vscode_amd:
    profiles: [ "amd" ]
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ghcr.io/scr255/vscode-uv-container:amd64-ubuntu24.04-py3.13-consume
    image: vscode-uv-expanded:amd64-cpu
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace/bind
    restart: unless-stopped

  # OpenVSCode — CPU profile ARM
  vscode_arm:
    profiles: [ "arm" ]
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ghcr.io/scr255/vscode-uv-container:arm64-ubuntu24.04-py3.13-consume
    image: vscode-uv-expanded:arm64-cpu
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace/bind
    restart: unless-stopped

  # OpenVSCode — GPU profile AMD
  vscode_amd_gpu:
    profiles: [ "amd_gpu" ]
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ghcr.io/scr255/vscode-uv-container:amd64-ubuntu24.04-py3.13-cu12.6.3-consume
    image: vscode-uv-expanded:amd64-gpu
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace/bind
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    gpus: all
    restart: unless-stopped
